language: node_js
node_js:
  - "8"
dist: trusty   # needed for chrome headless
sudo: required # needed for chrome headless
addons:
  firefox: latest
  chrome: stable
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-contrib-10
    # the following are mastodon dependencies
    - imagemagick
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - file
    - g++
    - libprotobuf-dev
    - protobuf-compiler
    - pkg-config nodejs
    - gcc
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
    - redis-tools
    - libidn11-dev
    - libicu-dev
services:
  - redis-server
before_install:
  - rvm install 2.5.0
  - rvm use 2.5.0
  - sudo -E add-apt-repository -y ppa:mc3man/trusty-media
  - sudo -E apt-get update
  - sudo -E apt-get install -y ffmpeg gstreamer0.10-ffmpeg
  - ruby --version
  - node --version
  - postgres --version
  - redis-server --version
  - ffmpeg -version
before_script:
  - npm run lint
script: npm run test-browser
env:
  global:
  - PGPORT=5433
matrix:
  include:
    - env: BROWSER=chrome:headless
    - env: BROWSER=firefox:headless
  allow_failures:
    - env: BROWSER=firefox:headless
branches:
  only:
  - master
  - /^greenkeeper/.*$/
cache:
  directories:
  - $HOME/.npm
  - $HOME/.rvm
  - $HOME/.bundle
  - $HOME/.yarn-cache
